safe: true
auto: true

source: .
destination: ./_site
baseurl: /

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title

title: Kangda's Blog
url: http://kang-da.tk
feed: /atom.xml

redcarpet:
extension: []
